### ISSUE TITLE
IE11: More data

### ISSUE THREAD

**Issue by syranide** [spicyj/innerhtml-vs-createelement-vs-clonenode#1]
The few appends that are there take up the majority of the time spent. Even more interestingly, the order in which you do it also has a _significant_ impact, see below:

``` js
// no append
// only create (41ms), create and set properties (243ms)

// append bottom up
// only create (222ms), create and set properties (541ms)
node22.appendChild(node23);
node23.appendChild(node24);
node24.appendChild(node25);
node22.appendChild(node26);
node26.appendChild(node27);
node27.appendChild(node28);
node26.appendChild(node29);
node29.appendChild(node30);

// append top down
// only create (574ms), create and set properties (930ms)
node29.appendChild(node30);
node26.appendChild(node29);
node27.appendChild(node28);
node26.appendChild(node27);
node22.appendChild(node26);
node24.appendChild(node25);
node23.appendChild(node24);
node22.appendChild(node23);
```

**Comment by syranide** [comment]
cc @spicyj

**Comment by sophiebits** [comment]
Wow! @localvoid tweeted me about the same thing:

https://twitter.com/localvoid/status/657088827740303360

I guess a lot of the internal structure needs to be changed whenever a node is moved – like they store the complete ancestor path or something?

**Comment by sophiebits** [comment]
Does it make a difference if you append before attribute setting instead of after?

**Comment by syranide** [comment]
> Does it make a difference if you append before attribute setting instead of after?

@spicyj Not in any measurably good/bad way it seemed, tried real quick with document fragments too.

**Comment by syranide** [comment]
@spicyj It could be worth double-checking that these costs doesn't continue to increase as the depth increases... that would be really bad.

**Comment by sophiebits** [comment]
Your "append bottom up" suggests 541 - 222 = 319ms is taken for attribute setting, while "append top down" takes 930 - 574 = 356ms. Maybe those are just within the margin of error?

**Comment by syranide** [comment]
@spicyj Yeah, the times varied slightly during different times of my testing so I wouldn't trust those numbers too much. It's possible that there are marginal gains, but it wasn't immediately apparent at least. I wouldn't expect setting attributes would be affected by children.
